services:
  ichat:
    image: ghcr.io/isomoes/ichat-web:latest
    # build:
    #   context: .
    #   dockerfile: ./package/Dockerfile
    restart: on-failure:3
    environment:
      - "NEWAPI_AUTH_BASE=https://aiapi.xxxx.top/"
      - "API_BASE=https://aiapi.xxxx.top"
    volumes:
      - "./data:/data"
    ports:
      - "3000:80"
